// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClqJpLEJP9gyI8cNVzI7bZ8w6Q_tvR_2s',
    appId: '1:451753610369:android:eccba216d4c81f5737d180',
    messagingSenderId: '451753610369',
    projectId: 'rutas360-622fd',
    storageBucket: 'rutas360-622fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnldZhd5z_o2FrxzW_CJtoIxyw5TAXPmE',
    appId: '1:451753610369:ios:ada415f551b8aa7437d180',
    messagingSenderId: '451753610369',
    projectId: 'rutas360-622fd',
    storageBucket: 'rutas360-622fd.firebasestorage.app',
    iosBundleId: 'com.example.consultoriaChatBot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnldZhd5z_o2FrxzW_CJtoIxyw5TAXPmE',
    appId: '1:451753610369:ios:ada415f551b8aa7437d180',
    messagingSenderId: '451753610369',
    projectId: 'rutas360-622fd',
    storageBucket: 'rutas360-622fd.firebasestorage.app',
    iosBundleId: 'com.example.consultoriaChatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr2UlOf1kel9eKKxJ-xOofNODQ--SoqFM',
    appId: '1:451753610369:web:6634c438d009cc1437d180',
    messagingSenderId: '451753610369',
    projectId: 'rutas360-622fd',
    authDomain: 'rutas360-622fd.firebaseapp.com',
    storageBucket: 'rutas360-622fd.firebasestorage.app',
  );

}