// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0BGN8m190lbiBxL341xhT4ZsYRcF8_AM',
    appId: '1:597064504946:android:712eb2ac546871b993d4eb',
    messagingSenderId: '597064504946',
    projectId: 'chatbot-colbun',
    storageBucket: 'chatbot-colbun.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAIZUCVQRzOtIIZ8g7Gzwdp3i8hNHaGZs',
    appId: '1:597064504946:ios:643ac1907e5bab4393d4eb',
    messagingSenderId: '597064504946',
    projectId: 'chatbot-colbun',
    storageBucket: 'chatbot-colbun.firebasestorage.app',
    iosBundleId: 'com.example.consultoriaChatBot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9_fkcJ3eCJtVL6Gn_vvLLGptxXJjQZ2I',
    appId: '1:597064504946:web:3a1b9c801e72c98b93d4eb',
    messagingSenderId: '597064504946',
    projectId: 'chatbot-colbun',
    authDomain: 'chatbot-colbun.firebaseapp.com',
    storageBucket: 'chatbot-colbun.firebasestorage.app',
    measurementId: 'G-6HBZ8N1CR9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAIZUCVQRzOtIIZ8g7Gzwdp3i8hNHaGZs',
    appId: '1:597064504946:ios:643ac1907e5bab4393d4eb',
    messagingSenderId: '597064504946',
    projectId: 'chatbot-colbun',
    storageBucket: 'chatbot-colbun.firebasestorage.app',
    iosBundleId: 'com.example.consultoriaChatBot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9_fkcJ3eCJtVL6Gn_vvLLGptxXJjQZ2I',
    appId: '1:597064504946:web:4afc02609c78e24393d4eb',
    messagingSenderId: '597064504946',
    projectId: 'chatbot-colbun',
    authDomain: 'chatbot-colbun.firebaseapp.com',
    storageBucket: 'chatbot-colbun.firebasestorage.app',
    measurementId: 'G-R24Z44DBCD',
  );

}